# version: '3.8'

services:
  ai-model:
    build: .
    container_name: ai-container
    volumes:
      - ./models:/models
      - ./scripts:/app/scripts
      - ./config.json:/app/config.json
    ports:
      - "5000:5000"
    environment:
      - MODEL_NAME=${MODEL_NAME}
      - MODEL_VERSION=${MODEL_VERSION}
    command: /bin/bash -c "/app/scripts/download_models.sh && /app/scripts/run_model.sh"
